= Widgets
:experimental:

In TigerGraph Insights, widgets populate pages to provide easy-to-use graph visualizations for your data.

Widgets work similarly to query visualizers. 
After creating a widget, you create a query for it to display on your page and for users to interact with.

This page explains the types of widgets available to you with Insights and best practices for the use of each one.

== Create a Widget

Each application page can have up to 20 widgets. Click on the btn:[+] icon in the lower left corner of the page view to choose a new type of widget to add.

After creation, you can move and resize the widget appearance on your page.

== Create and save a query

As you create a widget, you will be prompted to enter a query for it to visualize.
Different data types lend themselves to different visualization formats (see Types of Widgets for more information).


== Types of widgets

=== xref:graph-widget.adoc[]

Shows graph data as a connected network of vertices and edges that can be rearranged into any shape.
Accepts data as vertices and edges.

=== xref:map-widget.adoc[]

Overlays graph data on a map.
Accepts data as vertices and edges as long as each one has a numeric attribute to be interpreted as latitude and longitude.

=== xref:table-widget.adoc[]

Displays vertices as a relational table, similar to a spreadsheet.
Supports any input data format.

=== xref:single-value.adoc[]

Displays the first attribute of the first vertex or edge in a query result.
Ideal for displaying total counts or other summary values from a query.

=== xref:line-chart.adoc[]

Displays a standard line chart.
Accepts data as vertices and edges or a list of objects that contain at least one numeric attribute.

=== xref:bar-chart.adoc[]

Displays a standard bar chart.
Accepts data as vertices and edges or a list of objects that contain at least one numeric attribute.

=== xref:pie-chart.adoc[]

Displays a standard pie chart.
Accepts data as vertices and edges or a list of objects that contain at least one numeric attribute.

=== xref:sankey.adoc[]

Displays a Sankey chart, ideal for displaying flow from one set of values to another.
Accepts data as vertices and edges.

=== xref:inputs.adoc[]

An interactive widget that takes user input and uses it to drive queries in other widgets.
Supports any input data format.